project_id = "nlpczneghixtbwtsrqxl"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.review-kr]
    verify_jwt = true
